/// <reference types="vite/client" />
import { Actor, ActorSubclass } from '@dfinity/agent';
import { getAgent } from './agent';

// ✅ Workstream 1: Successfully generated and uncommented!
// @ts-ignore: Declarations are generated by dfx build and might not be committed to Git
import { _SERVICE } from '../declarations/medvault_backend/medvault_backend.did.js';
// @ts-ignore: Declarations are generated by dfx build and might not be committed to Git
import { idlFactory } from '../declarations/medvault_backend/index.js';

export type MedVaultBackend = _SERVICE;

import { MEDVAULT_BACKEND_CANISTER_ID } from './env';

const CANISTER_ID = MEDVAULT_BACKEND_CANISTER_ID;

if (!CANISTER_ID) {
  console.warn("MEDVAULT_BACKEND_CANISTER_ID is not defined in the environment.");
}
let backendActorInstance: ActorSubclass<MedVaultBackend> | null = null;

/**
 * Initializes and returns the backend Actor instance.
 */
export const getBackendActor = async (): Promise<ActorSubclass<MedVaultBackend>> => {
  if (backendActorInstance) {
    return backendActorInstance;
  }

  const agent = await getAgent();

  backendActorInstance = Actor.createActor<MedVaultBackend>(idlFactory, {
    agent,
    canisterId: CANISTER_ID,
  });

  return backendActorInstance;
};

/**
 * Force recreates the actor. Useful when identity changes.
 */
export const recreateActor = async (): Promise<ActorSubclass<MedVaultBackend>> => {
  backendActorInstance = null;
  return getBackendActor();
};

// TODO (Workstream 3): Add specific typed helper functions here for interacting with canister methods 
// e.g., export const getRecords = async () => { ... }
