import { Actor, ActorSubclass } from '@dfinity/agent';
import { getAgent } from './agent';

// TODO (Workstream 1 -> Workstream 2 Handoff): 
// Workstream 1 instructions state:
// 1. Sync Declarations: Use the auto-generated files inside `client/src/declarations/medvault_backend/` (specifically `medvault_backend.did.js` and `medvault_backend.did.d.ts`) created by `dfx build`.
// 2. Initialize the Actor: Import the `idlFactory` from those declarations and pass it into `@dfinity/agent`'s `Actor.createActor()` method.
// 3. Handle Env Vars: Ensure `MEDVAULT_BACKEND_CANISTER_ID` is loaded from the `.env` file generated by `dfx deploy`.

// Currently, the declarations directory does not exist, so we keep these commented out.
// import { _SERVICE } from '../../declarations/medvault_backend/medvault_backend.did';
// import { idlFactory } from '../../declarations/medvault_backend';

// Temporary type stub
export type MedVaultBackend = any; // Replace with _SERVICE later
const idlFactory = ({ IDL }: any) => IDL.Service({}); // Replace with actual idlFactory

const CANISTER_ID = process.env.MEDVAULT_BACKEND_CANISTER_ID || 'dummy-canister-id';

let backendActorInstance: ActorSubclass<MedVaultBackend> | null = null;

/**
 * Initializes and returns the backend Actor instance.
 */
export const getBackendActor = async (): Promise<ActorSubclass<MedVaultBackend>> => {
  if (backendActorInstance) {
    return backendActorInstance;
  }

  const agent = await getAgent();

  backendActorInstance = Actor.createActor<MedVaultBackend>(idlFactory, {
    agent,
    canisterId: CANISTER_ID,
  });

  return backendActorInstance;
};

/**
 * Force recreates the actor. Useful when identity changes.
 */
export const recreateActor = async (): Promise<ActorSubclass<MedVaultBackend>> => {
  backendActorInstance = null;
  return getBackendActor();
};

// TODO (Workstream 3): Add specific typed helper functions here for interacting with canister methods 
// e.g., export const getRecords = async () => { ... }
