version: '3.8'

services:
  medvault-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: medvault_dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
    ports:
      - "4943:4943"
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "dfx start --host 127.0.0.1:4943 --background && dfx deploy && cd client && npm install && npm run dev -- --host 0.0.0.0"

volumes:
  node_modules:
  client_node_modules:
