// =============================================================================
// MedVault — Notification Store
// Workstream 3: Client State & Integration
//
// Manages two distinct notification surfaces:
//   1. Toast queue  — transient success/error/warning/info messages
//   2. Emergency banner — persistent high-visibility break-glass alert
//
// Consumed by (Workstream 4):
//   - Toast.tsx              — renders the notification queue
//   - AppShell.tsx / Header  — renders the emergency banner
//
// Consumed by (Workstream 3 hooks):
//   - useEmergency.ts        — calls showEmergencyBanner() on break-glass trigger
//   - useAccess.ts           — calls success()/error() on grant mutations
//   - useRecords.ts          — calls success()/error() on upload complete/fail
//
// ⚠️  FROZEN PUBLIC API — Notification field names are the W4 contract:
//   id, type, title, message, duration, dismissible, action, createdAt
// =============================================================================

import { create } from 'zustand';
import type { EmergencyNotification } from '../types/emergency';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type NotificationType = 'success' | 'error' | 'warning' | 'info' | 'emergency';

export interface Notification {
  /** Unique ID — generated via crypto.randomUUID() inside addNotification(). */
  id: string;

  type: NotificationType;

  /** Short heading text, e.g. "Upload complete". */
  title: string;

  /** Descriptive body text. */
  message: string;

  /**
   * Auto-dismiss delay in milliseconds.
   * null = notification is permanent until manually dismissed.
   * Default: 5000ms for success/info, 8000ms for warning, null for error/emergency.
   */
  duration: number | null;

  /**
   * Optional call-to-action shown inside the toast.
   * e.g. { label: 'View Record', onClick: () => navigate('/records/123') }
   */
  action?: {
    label: string;
    onClick: () => void;
  };

  /**
   * Whether the user can manually close this notification.
   * Always true for toasts; false for system-generated emergency alerts.
   */
  dismissible: boolean;

  /** Unix timestamp (ms) — Date.now() at creation time. */
  createdAt: number;
}

/** Input for addNotification — id and createdAt are generated by the store. */
export type NotificationInput = Omit<Notification, 'id' | 'createdAt'>;

interface EmergencyBannerState {
  /** Whether the banner is currently visible. */
  visible: boolean;
  /**
   * The emergency event that triggered the banner.
   * Kept even when `visible = false` so the patient can re-read it via UI.
   */
  event: EmergencyNotification | null;
}

interface NotificationState {
  notifications: Notification[];
  emergencyBanner: EmergencyBannerState;
}

interface NotificationActions {
  /**
   * Add a notification to the queue.
   * Returns the generated notification `id` so callers can
   * programmatically remove it (e.g. "update to done" pattern).
   */
  addNotification: (input: NotificationInput) => string;

  /** Manually remove a notification by id. */
  removeNotification: (id: string) => void;

  /** Remove all non-emergency notifications from the queue. */
  clearAll: () => void;

  /**
   * Display the persistent emergency banner.
   * Called by useEmergency.ts when a doctor triggers break-glass access.
   */
  showEmergencyBanner: (event: EmergencyNotification) => void;

  /**
   * Hide the emergency banner.
   * Does NOT clear the stored event — it stays available for re-display.
   */
  dismissEmergencyBanner: () => void;

  // --- Shorthand helpers (Workstream 3 hooks and W4 components use these) ---

  /** Show a green success toast. Returns notification id. */
  success: (title: string, message: string, duration?: number) => string;

  /** Show a red error toast (permanent — requires manual dismiss). */
  error: (title: string, message: string) => string;

  /** Show a yellow warning toast. */
  warning: (title: string, message: string, duration?: number) => string;

  /** Show a blue info toast. */
  info: (title: string, message: string, duration?: number) => string;
}

export type NotificationStore = NotificationState & NotificationActions;

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useNotificationStore = create<NotificationStore>()((set, get) => ({
  // --- State ---
  notifications: [],
  emergencyBanner: {
    visible: false,
    event: null,
  },

  // --- Actions ---
  addNotification: (input) => {
    const id = crypto.randomUUID();
    const notification: Notification = {
      ...input,
      id,
      createdAt: Date.now(),
    };

    set((state) => ({
      notifications: [...state.notifications, notification],
    }));

    // Auto-dismiss side effect: schedule removal after `duration` ms.
    // The setTimeout id is intentionally NOT stored in Zustand state —
    // it is a side effect, not reactive state.
    if (notification.duration !== null) {
      window.setTimeout(() => {
        get().removeNotification(id);
      }, notification.duration);
    }

    return id;
  },

  removeNotification: (id) => {
    set((state) => ({
      notifications: state.notifications.filter((n) => n.id !== id),
    }));
  },

  clearAll: () => {
    set({ notifications: [] });
  },

  showEmergencyBanner: (event) => {
    set({ emergencyBanner: { visible: true, event } });
  },

  dismissEmergencyBanner: () => {
    set((state) => ({
      emergencyBanner: { ...state.emergencyBanner, visible: false },
    }));
  },

  // --- Shorthand helpers ---
  success: (title, message, duration = 5000) => {
    return get().addNotification({
      type: 'success',
      title,
      message,
      duration,
      dismissible: true,
    });
  },

  error: (title, message) => {
    return get().addNotification({
      type: 'error',
      title,
      message,
      duration: null, // Errors are permanent — user must acknowledge
      dismissible: true,
    });
  },

  warning: (title, message, duration = 8000) => {
    return get().addNotification({
      type: 'warning',
      title,
      message,
      duration,
      dismissible: true,
    });
  },

  info: (title, message, duration = 5000) => {
    return get().addNotification({
      type: 'info',
      title,
      message,
      duration,
      dismissible: true,
    });
  },
}));
